import type { TagRepository } from "./card_types"

function createLanguageTag(display: string) {
    return {
        icon: "nf-md-language_" + display.toLowerCase(),
        display: display,
        description: `Has code written in the ${display} programming language`
    }
}

export const TAGS: TagRepository = {
    ai_assisted: {
        icon: "nf-fa-robot",
        display: "AI-Assisted",
        description: "Some of the project's code was generated by AI. All generated code was manually reviewed.",
        style: "color: #D4C092",
    },

    ai_generated: {
        icon: "nf-fa-robot",
        display: "AI-Generated",
        description: "A substantial amount (but not all) of the project's code was generated by AI with minor review.",
        style: "color: #BA5959",
    },

    lua: createLanguageTag("Lua"),
    python: createLanguageTag("Python"),
    java: createLanguageTag("Java"),
    javascript: createLanguageTag("JavaScript"),
    typescript: createLanguageTag("TypeScript"),

    legacy: {
        icon: "nf-cod-arrow_left",
        display: "Legacy",
        description: "Old code from long ago; don't expect me to update this."
    },

    library: {
        icon: "nf-md-tools",
        display: "Library/Tool",
        description: "A library or tool that is used by other projects."
    },

    closed_source: {
        icon: "nf-oct-eye_closed",
        display: "Closed Source",
        description: "The source code of the project is not publicly visible, but usually has a downloadable/playable binary."
    }
}
